name: CI

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  qa-py:
    name: Python QA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: |
          uv sync --all-extras --dev
          uv tool install poethepoet

      - name: Check formatting & linting
        run: poe check

      - name: Notebooks - check for unnecessary metadata and empty cells
        run: poe nbcheck

      - name: Unit tests
        run: poe test

      - name: Run notebooks to see if they execute without errors
        run: poe nbrun
